# Generated by Django 4.2.13 on 2024-06-09 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="zeugnisItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=datetime.date.today)),
                ("category", models.CharField(max_length=1000)),
                ("grading", models.SmallIntegerField(default=0)),
            ],
        ),
    ]
