# Generated by Django 4.2.13 on 2024-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zeugnisitem",
            name="person",
            field=models.CharField(default="leer", max_length=200),
        ),
    ]
