# Generated by Django 4.2.13 on 2024-06-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackgeber",
            options={},
        ),
    ]
