# Generated by Django 4.2.13 on 2024-06-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0002_alter_feedbackgeber_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="feedbackGeber",
        ),
    ]
