# Generated by Django 4.2.13 on 2024-06-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0002_zeugnisitem_person"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="zeugnisItem",
            new_name="feedbackItem",
        ),
    ]
