# Generated by Django 4.2.13 on 2024-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0003_rename_zeugnisitem_feedbackitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="mitarbeiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(default="leer", max_length=200)),
                ("name", models.CharField(default="leer", max_length=200)),
            ],
        ),
    ]
