# Generated by Django 4.2.13 on 2024-06-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0004_mitarbeiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="mitarbeiter",
            name="initial",
            field=models.CharField(default="leer", max_length=200),
        ),
    ]
