# Generated by Django 4.2.13 on 2024-06-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0005_alter_feedbackgeber_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackgeber",
            name="bewertet",
            field=models.BooleanField(default=False),
        ),
    ]
