# Generated by Django 4.2.13 on 2024-06-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0007_feedbackgeber_user_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackgeber",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
