# Generated by Django 4.2.13 on 2024-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0008_remove_feedbackgeber_user_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackitem",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
