# Generated by Django 4.2.13 on 2024-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0010_alter_feedbackgeber_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackgeber",
            name="partner",
            field=models.BooleanField(default=False),
        ),
    ]
