# Generated by Django 4.2.13 on 2024-07-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zeugnis", "0012_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Fragenkatalog",
        ),
        migrations.AlterModelOptions(
            name="fragenkatalog",
            options={"verbose_name_plural": "Fragenkatalog"},
        ),
    ]
